/*!\file	CaseSvcField.h
*  \brief	系统定义
*  \date	2010年10月30日22:00:44
*  \author	Stuarts
*  \version 1.0
*/
#pragma once

#define FIELD_TEST_CASE 10000

enum E_FILED_CASELIBRARY
{
	// 案例基本信息
	FIELD_CASELIBRARY_PLATNO		= 1000,
	FIELD_CASELIBRARY_FACTORY,
	FIELD_CASELIBRARY_COMPANY,
	FIELD_CASELIBRARY_CASE_NAME,
	FIELD_CASELIBRARY_CASE_DETAIL,
	FIELD_CASELIBRARY_CASE_TIME,
	FIELD_CASELIBRARY_CASE_INPUT_USER,
	FIELD_CASELIBRARY_CASE_INPUT_TIME,
	FIELD_CASELIBRARY_CASE_ID,
	FIELD_CASELIBRARY_CASE_ID_ARRAY,

	// 故障
	FIELD_CASELIBRARY_FAULT_ID,


	// 征兆
	FIELD_CASELIBRARY_SYMPTOM_ID,
	FIELD_CASELIBRARY_SYMPTOM_VALUE_ID,
	FIELD_CASELIBRARY_SYMPTOM_IMPORTANT_DEGREE,		// 征兆重要度
	FIELD_CASELIBRARY_CASE_SYMPTOM_COUNT,			// 该案例征兆数量
	FIELD_CASELIBRARY_CASE_SYMPTOM_INDEX,			// 征兆在该案例所有征兆中的索引
	FIELD_CASELIBRARY_CASE_SYMPTOM_MATRIX,			// 该案例征兆矩阵中当前征兆所在行数据

	FIELD_CASELIBRARY_SYMPTOM_BUFFER,				// 征兆BUFFER数据，基于案例推理
	FIELD_CASELIBRARY_CBR_SIMILARITY,				// 案例相似度


	// 附件
	FIELD_CASELIBRARY_ATTACHMENT_NAME,
	FIELD_CASELIBRARY_ATTACHMENT_FILE_NAME,
	FIELD_CASELIBRARY_ATTACHMENT_TYPE,
	FIELD_CASELIBRARY_ATTACHMENT_CHANN_INFO,
	FIELD_CASELIBRARY_ATTACHMENT_SIZE,

	FIELD_CASELIBRARY_ATTACHMENT_SIZE_TOTAL,		// 附件总大小
	FIELD_CASELIBRARY_ATTACHMENT_SIZE_TRANSFERED,	// 已经传输完成的附件大小
	FIELD_CASELIBRARY_ATTACHMENT_SIZE_TRANSFERRING,	// 正在传输的数据大小
	FIELD_CASELIBRARY_ATTACHMENT_DATA,				// 附件数据
	FIELD_CASELIBRARY_ATTACHMENT_DATA_KEY,			// 附件buffer map的key  GUID对象

	// 案例审核
	FIELD_CASELIBRARY_CASE_STATUS,
	FIELD_CASELIBRARY_CASE_VERIFY_USERNAME,
	FIELD_CASELIBRARY_CASE_VERIFY_TIME,

	// 检维修记录
	FIELD_CASELIBRARY_MAINTENANCE_RECORD_ID,
	FIELD_CASELIBRARY_MAINTENANCE_RECORD_NAME,
	FIELD_CASELIBRARY_MAINTENANCE_TYPE,
	FIELD_CASELIBRARY_MAINTENANCE_SECTION,
	FIELD_CASELIBRARY_MAINTENANCE_BEGIN_TIME,
	FIELD_CASELIBRARY_MAINTENANCE_END_TIME,
	FIELD_CASELIBRARY_MAINTENANCE_CONTENT,
	FIELD_CASELIBRARY_MAINTENANCE_REASON,
	FIELD_CASELIBRARY_MAINTENANCE_FAULT_ID,
	FIELD_CASELIBRARY_MAINTENANCE_RESULT,
	FIELD_CASELIBRARY_MAINTENANCE_MAIN_PEOPLE,
	FIELD_CASELIBRARY_MAINTENANCE_OTHER_PEOPLE,
	FIELD_CASELIBRARY_MAINTENANCE_REMARK,
	FIELD_CASELIBRARY_MAINTENANCE_ADD_RECORD_TIME,
	FIELD_CASELIBRARY_MAINTENANCE_RECORDER,

	// 开停车记录
	FIELD_CASELIBRARY_SUD_RECORD_ID,
	FIELD_CASELIBRARY_SUD_TIME,
	FIELD_CASELIBRARY_SUD_TYPE,
	FIELD_CASELIBRARY_SUD_REASON,
	FIELD_CASELIBRARY_SUD_FAULT_ID,
	FIELD_CASELIBRARY_SUD_REMARK,
	FIELD_CASELIBRARY_SUD_RECORDER,

	// 查询
	FIELD_CASELIBRARY_QUERY_BEGIN_TIME,
	FIELD_CASELIBRARY_QUERY_END_TIME,

	// 结果
	FIELD_CASELIBRARY_RESULT,
	FIELD_CASELIBRARY_ERROR_MSG,
};